In [1]:
import pandas as pd

In [9]:
value_mapping = {
    'United States': 'US',
    'Alabama': 'AL',
    'Alaska': 'AK', 
    'Arizona': 'AZ', 
    'Arkansas': 'AR', 
    'California': 'CA',
    'Colorado': 'CO', 
    'Connecticut': 'CT', 
    'Delaware': 'DE', 
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI', 
    'Idaho': 'ID', 
    'Illinois': 'IL',
    'Indiana': 'IN', 
    'Iowa': 'IA', 
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI', 
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

In [ ]:
def clean_csv(filepath, valuemapping, format='Percent', column_name=None):
    df = pd.read_excel(filepath)
    df['Location'] = df['Location'].replace(valuemapping)
    if yearmap:
        df['TimeFrame'] = df['TimeFrame'].replace(year_map)
    df['LocYear'] = df['Location'].astype(str) + df['TimeFrame'].astype(str)
    result = df[df['DataFormat'] == format].pivot_table(
        index='LocYear', 
        columns=column_name, 
        values='Data', 
        aggfunc='sum'
    )
    result.columns.name = None
    result = result.reset_index()
    return result

In [18]:
df = pd.read_csv("data/gunownerdata.csv")
df['STATE'] = df['STATE'].replace(value_mapping)
df['LocYear'] = df['STATE'].astype(str) + df['Year'].astype(str)

In [19]:
df

,FIP,Year,STATE,HFR,HFR_se,universl,permit,Fem_FS_S,Male_FS_S,BRFSS,...,GSS,PEW,HuntLic,GunsAmmo,BackChk,PewQChng,BS1,BS2,BS3,LocYear
0,1,1980,AL,0.608,0.031,0,0,0.824324,0.833795,-9.0,...,0.583632,-9.000000,0.291102,-0.509164,-9.000000,0,0.0,0.0,0.0,AL1980
1,1,1981,AL,0.597,0.047,0,0,0.692308,0.831126,-9.0,...,-9.000000,-9.000000,0.294962,-0.618954,-9.000000,0,1.0,0.0,0.0,AL1981
2,1,1982,AL,0.661,0.036,0,0,0.771739,0.821429,-9.0,...,0.655196,-9.000000,0.290545,-0.526692,-9.000000,0,2.0,0.0,0.0,AL1982
3,1,1983,AL,0.586,0.038,0,0,0.688172,0.819277,-9.0,...,-9.000000,-9.000000,0.284983,-0.713227,-9.000000,0,3.0,0.0,0.0,AL1983
4,1,1984,AL,0.624,0.036,0,0,0.710000,0.775956,-9.0,...,0.626933,-9.000000,0.281622,-0.733305,-9.000000,0,4.0,0.0,0.0,AL1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845,56,2012,WY,0.597,0.029,0,0,0.375000,0.647482,-9.0,...,-9.000000,0.622224,0.545627,2.973924,1.562481,0,12.0,12.0,8.0,WY2012
1846,56,2013,WY,0.613,0.032,0,0,0.529412,0.714286,-9.0,...,-9.000000,0.685266,0.542697,3.066252,1.638737,1,12.0,12.0,9.0,WY2013
1847,56,2014,WY,0.608,0.044,0,0,0.583333,0.666667,-9.0,...,-9.000000,-9.000000,0.538761,3.092854,1.603822,1,12.0,12.0,10.0,WY2014
1848,56,2015,WY,0.549,0.032,0,0,0.393939,0.661290,-9.0,...,-9.000000,0.611531,0.544356,2.910414,1.348323,1,12.0,12.0,11.0,WY2015
1849,56,2016,WY,0.607,0.032,0,0,0.375000,0.669643,-9.0,...,-9.000000,0.725993,0.538439,2.899840,1.265807,1,12.0,12.0,12.0,WY2016

In [20]:
df = df[df['Year'] >= 2010]
df.drop(columns=['STATE', 'Year'])

,FIP,HFR,HFR_se,universl,permit,Fem_FS_S,Male_FS_S,BRFSS,GALLUP,GSS,PEW,HuntLic,GunsAmmo,BackChk,PewQChng,BS1,BS2,BS3,LocYear
30,1,0.456,0.028,0,0,0.546099,0.700743,-9.0,-9.000000,0.391567,0.486040,0.225767,-0.250093,1.057550,0,12.0,12.0,6.0,AL2010
31,1,0.513,0.032,0,0,0.653226,0.700000,-9.0,-9.000000,-9.000000,0.536971,0.349485,-0.260119,0.975045,0,12.0,12.0,7.0,AL2011
32,1,0.543,0.026,0,0,0.623188,0.706485,-9.0,0.631616,0.496401,0.558550,0.344020,-0.215208,1.066323,0,12.0,12.0,8.0,AL2012
33,1,0.516,0.032,0,0,0.562092,0.735915,-9.0,-9.000000,-9.000000,0.598503,0.344332,-0.172469,1.202040,1,12.0,12.0,9.0,AL2013
34,1,0.510,0.035,0,0,0.595890,0.688928,-9.0,-9.000000,0.467335,-9.000000,0.340475,-0.196054,1.242362,1,12.0,12.0,10.0,AL2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845,56,0.597,0.029,0,0,0.375000,0.647482,-9.0,0.662060,-9.000000,0.622224,0.545627,2.973924,1.562481,0,12.0,12.0,8.0,WY2012
1846,56,0.613,0.032,0,0,0.529412,0.714286,-9.0,-9.000000,-9.000000,0.685266,0.542697,3.066252,1.638737,1,12.0,12.0,9.0,WY2013
1847,56,0.608,0.044,0,0,0.583333,0.666667,-9.0,-9.000000,-9.000000,-9.000000,0.538761,3.092854,1.603822,1,12.0,12.0,10.0,WY2014
1848,56,0.549,0.032,0,0,0.393939,0.661290,-9.0,-9.000000,-9.000000,0.611531,0.544356,2.910414,1.348323,1,12.0,12.0,11.0,WY2015
1849,56,0.607,0.032,0,0,0.375000,0.669643,-9.0,-9.000000,-9.000000,0.725993,0.538439,2.899840,1.265807,1,12.0,12.0,12.0,WY2016

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 350 entries, 30 to 1849
Data columns (total 21 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   FIP        350 non-null    int64
 1   Year       350 non-null    int64
 2   STATE      350 non-null    str
 3   HFR        350 non-null    float64
 4   HFR_se     350 non-null    float64
 5   universl   350 non-null    int64
 6   permit     350 non-null    int64
 7   Fem_FS_S   350 non-null    float64
 8   Male_FS_S  350 non-null    float64
 9   BRFSS      350 non-null    float64
 10  GALLUP     350 non-null    float64
 11  GSS        350 non-null    float64
 12  PEW        350 non-null    float64
 13  HuntLic    350 non-null    float64
 14  GunsAmmo   350 non-null    float64
 15  BackChk    350 non-null    float64
 16  PewQChng   350 non-null    int64
 17  BS1        350 non-null    float64
 18  BS2        350 non-null    float64
 19  BS3        350 non-null    float64
 20  LocYear    350 non-null    str
dtypes: float64(14), int64(5), str(2)
memory usage: 63.0 KB

In [7]:
money_df = pd.read_excel("data/Table.xlsx")

In [8]:
money_df

,GeoFIPS,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,0,United States,7584003.0,7978449.0,8620234.0,8990104.0,9146700.0,9474684.0,10008929.0,10540800.0,...,15884741.0,16658962.0,17514402.0,18349584.0,19613059.0,21484168.0,22144814.0,23577208.0,24897613.0,26109831.2
1,1000,Alabama,99772.9,103204.1,108002.9,111894.1,115007.7,120241.0,128606.3,136087.5,...,190871.8,197963.8,205674.2,215151.8,230878.4,255682.3,262425.8,279484.6,295590.5,309906.4
2,2000,Alaska,18155.9,18706.6,20092.2,21287.1,22331.5,23372.1,24429.2,26019.6,...,41285.5,41919.4,43522.7,44459.7,45375.8,48327.1,50793.7,53322.0,56423.1,59110.5
3,4000,Arizona,117835.0,124922.3,135573.8,142097.8,147455.2,156408.8,170443.0,187724.9,...,279696.7,297261.5,315459.0,337257.2,374282.4,415893.1,435718.7,471040.2,498903.6,520574.1
4,5000,Arkansas,55686.3,57922.1,60886.2,64168.6,65698.8,69656.4,74308.7,77990.4,...,119758.8,123825.4,128970.8,131394.8,142072.2,161493.9,163688.6,173568.3,183201.8,192345.6
5,6000,California,953360.5,1022682.7,1127550.1,1169366.4,1187280.9,1240604.2,1315172.2,1387883.8,...,2191138.0,2295048.7,2411055.1,2539747.4,2770488.8,3019215.7,3021645.5,3182779.3,3400237.3,3585890.9
6,8000,Colorado,122577.9,131712.8,146560.8,154066.7,154492.3,157405.3,163568.5,174247.8,...,283678.7,303366.7,328112.7,351476.0,374449.3,418190.2,448676.8,473104.6,494798.6,518167.9
7,9000,Connecticut,126666.4,133690.1,146216.9,154585.9,154452.8,156438.6,164657.4,173328.8,...,243698.7,249451.1,260582.2,267564.2,275029.8,296291.5,309011.4,328729.9,349377.1,364716.0
8,10000,Delaware,22475.7,24116.7,26586.9,29374.8,30360.3,31071.8,32271.3,33073.3,...,45928.4,48077.1,51150.4,52774.4,55069.8,60175.9,65386.9,66943.8,71594.2,75635.2
9,11000,District of Columbia,21514.7,22625.2,24827.6,25742.9,25863.4,26138.6,28379.7,29880.4,...,52190.6,54158.7,56395.7,57511.2,60880.0,65682.9,68247.0,73296.2,78079.5,80546.6
10,12000,Florida,416721.5,435930.4,471588.1,497335.4,514288.8,540366.3,587003.0,637602.8,...,938985.6,1011002.2,1078010.6,1145938.8,1222053.4,1367061.9,1464251.0,1604650.3,1706305.7,1793464.1
11,13000,Georgia,205294.0,218718.6,236616.8,248742.5,255977.2,265622.8,280462.4,297084.9,...,441039.1,467592.5,491088.0,516504.2,552699.9,607184.3,627439.0,663930.9,704463.9,738993.1
12,15000,Hawaii,32355.7,33425.6,35403.1,36996.8,38865.6,40734.2,43729.2,46898.1,...,70744.8,73646.4,75266.4,78586.9,82758.5,88650.4,91007.9,96961.4,102703.8,109742.4
13,16000,Idaho,28498.1,30180.1,32667.0,34059.4,35213.9,36454.9,39386.7,41724.7,...,67294.1,71472.6,76529.6,82967.7,91960.1,105916.0,110891.1,116692.4,124746.7,131619.9
14,17000,Illinois,366594.1,382605.3,411220.9,427182.4,432381.6,440480.1,457834.3,475646.2,...,664686.8,685632.7,722686.6,741904.7,788153.3,849243.1,858844.4,907225.7,947182.8,989192.4
15,18000,Indiana,154521.8,160465.8,171032.1,175229.8,177918.8,182458.0,191088.3,196999.0,...,287275.2,297990.5,313127.2,326391.4,351576.3,391059.0,401573.6,422345.3,443688.8,462278.6
16,19000,Iowa,73147.5,74998.7,80082.6,82519.7,84518.2,86330.6,93377.9,96080.0,...,143839.9,147911.5,154686.0,158156.3,168097.8,186318.9,196040.1,201755.9,211425.4,221266.3
17,20000,Kansas,69711.2,71968.6,75870.8,78490.8,79285.4,81768.2,84076.9,88784.0,...,136753.6,141311.8,147407.4,153011.9,162277.2,173977.0,181747.0,187457.3,195633.0,206945.7
18,21000,Kentucky,89403.1,93175.0,100475.1,103997.8,106551.9,109765.9,116214.1,121734.5,...,175275.6,180836.1,186931.1,195518.9,212278.2,234113.4,237842.6,253319.5,267297.9,279513.8
19,22000,Louisiana,98863.5,101157.7,106907.7,114767.4,118194.3,122009.9,127386.9,137162.4,...,197411.9,203454.9,212320.8,219305.0,233449.5,255091.5,254415.5,270677.4,284587.2,295288.3
20,23000,Maine,31264.4,32675.4,35091.4,37055.0,38290.7,40162.9,42164.5,43103.5,...,59286.8,61740.1,64463.2,67852.8,74137.0,81887.1,85704.2,91602.3,96850.3,101392.7
21,24000,Maryland,163509.0,173125.8,188437.2,198926.9,206707.3,215973.4,230279.2,242214.0,...,344195.1,356079.0,367831.3,380447.2,400750.0,427803.2,438306.4,469239.6,496413.9,512715.9
22,25000,Massachusetts,205509.2,219633.3,244147.4,254058.1,252959.5,257918.0,270865.5,282138.1,...,438598.5,459778.7,483954.4,507884.7,542032.6,588651.0,600009.6,635619.8,667993.0,697205.3
23,26000,Michigan,268711.9,282128.9,301060.4,306670.4,306427.1,313961.0,322698.4,329235.3,...,441557.2,454894.8,474208.0,489569.6,532019.9,573255.7,583072.1,617163.2,645846.8,674070.6
24,27000,Minnesota,140269.1,147376.2,159595.4,166509.0,170085.2,177862.3,188674.9,193583.8,...,288866.6,301749.0,317564.8,329291.6,350470.0,387015.8,397877.4,418091.0,437981.9,457907.5
25,28000,Mississippi,56581.1,58494.4,61604.9,65064.1,66326.2,69011.9,73054.9,77635.0,...,106355.5,109132.8,111917.8,116213.5,125624.9,138640.2,138223.7,146160.9,153256.4,161093.5
26,29000,Missouri,140839.7,146172.5,156202.1,161531.2,165389.8,171593.2,180453.8,186770.9,...,267048.6,273774.2,286084.3,297492.6,321316.7,351191.9,361652.1,387601.3,405457.2,423808.7
27,30000,Montana,19125.7,19496.9,20770.5,21685.2,22350.3,24015.2,26072.2,28052.0,...,45283.3,48003.3,50352.0,53402.3,58241.5,65539.6,69666.5,74870.4,78741.6,82807.2
28,31000,Nebraska,44747.0,46824.4,49570.3,51911.8,52804.3,56102.2,58597.2,60598.1,...,93559.7,95823.7,100067.8,104615.9,111734.1,125057.8,130888.6,142166.5,145798.5,153082.3
29,32000,Nevada,54217.2,58623.6,64312.6,68026.7,69952.7,74518.4,82524.7,92194.1,...,129879.1,138847.0,148408.1,159393.0,170447.5,192132.9,199226.6,214392.7,228086.6,240111.7
30,33000,New Hampshire,36597.5,38930.2,43796.1,46179.9,46972.3,47833.0,50733.0,52464.3,...,75229.0,78661.0,82353.7,87724.1,93153.8,102663.3,105210.8,111148.6,117220.3,123076.5
31,34000,New Jersey,286580.2,299723.8,329591.8,341308.9,345988.7,354097.7,369770.9,382749.3,...,545301.7,566237.1,591910.4,625170.3,653214.2,707402.6,719848.2,765228.3,806558.7,842372.2
32,35000,New Mexico,38233.1,38915.1,41922.3,44958.8,46821.7,49019.7,52099.7,55540.8,...,80782.3,82354.1,86179.5,91208.9,98634.3,107674.3,112280.3,117634.3,124086.2,131026.8
33,36000,New York,600087.2,635242.7,683214.3,709417.6,707561.1,717555.3,749469.3,777653.2,...,1176654.7,1255776.7,1298669.0,1343851.2,1415644.9,1515619.3,1526280.6,1617130.9,1699680.0,1777164.5
34,37000,North Carolina,198232.0,207943.0,221516.2,228090.9,231930.9,241805.1,261603.4,280391.8,...,429054.9,449817.7,473093.3,501618.1,541462.5,604630.7,632926.5,677170.4,724994.6,767182.6
35,38000,North Dakota,15078.7,15257.9,16591.1,16930.7,17356.1,18949.5,19330.9,20501.4,...,39232.0,39743.7,42565.9,43997.2,47122.5,51468.4,55463.3,56452.5,57153.4,60077.4
36,39000,Ohio,298491.4,307407.0,323812.5,333209.3,338462.5,348428.7,361753.0,371633.8,...,521622.5,541289.4,562523.0,582299.9,623575.0,676718.3,685892.1,730013.2,766045.8,800799.1
37,40000,Oklahoma,74943.6,76956.5,83332.1,88609.5,90711.6,95275.7,102917.3,112487.6,...,164709.0,171995.4,180824.0,189996.8,198234.3,217902.1,233182.3,247300.5,260910.2,274858.0
38,41000,Oregon,86877.8,89931.4,96913.7,99785.7,101042.1,104729.6,110580.7,116073.4,...,186105.0,197262.3,210044.9,220029.4,240450.4,266544.6,270427.9,286979.9,302582.3,314868.7
39,42000,Pennsylvania,334421.8,348489.2,372690.7,388186.3,395633.3,409185.8,432634.7,450359.7,...,653328.9,671702.8,707043.4,729329.5,783389.5,833103.4,845037.9,885950.0,924379.6,969412.5
40,44000,Rhode Island,28349.7,29581.1,31875.3,33611.8,34965.7,36700.2,38541.5,39241.3,...,52514.5,54704.3,56918.9,60337.0,64996.8,69245.5,70880.1,74777.8,78553.7,82465.2
41,45000,South Carolina,89751.9,94148.5,100705.3,104242.1,107305.3,111196.7,117451.8,124417.0,...,200027.4,210387.6,219942.1,234295.4,250250.5,277322.6,288512.6,311235.5,332982.7,351926.0
42,46000,South Dakota,18102.9,18948.9,20201.2,20892.2,20898.5,22822.7,24553.2,26005.4,...,41551.5,42989.3,45144.0,48013.9,52908.8,60221.0,63454.7,68097.0,69996.3,74150.0
43,47000,Tennessee,139760.3,145231.9,153990.1,158125.3,162879.4,169929.5,179892.9,188177.6,...,286532.3,299307.7,316176.5,335601.7,360094.7,402024.7,417424.4,453765.7,480671.2,505698.3
44,48000,Texas,514882.6,543797.6,591738.3,631080.2,639443.1,664814.9,696381.3,754775.9,...,1276330.6,1367826.0,1463789.8,1537205.7,1602962.6,1786060.9,1920254.6,2074225.2,2184833.3,2294646.6
45,49000,Utah,48098.5,50670.0,54230.6,56788.7,58508.6,60770.4,64795.0,70661.8,...,126540.6,134546.7,144645.5,155711.5,169991.6,194799.1,206055.7,222237.8,235907.4,247691.4
46,50000,Vermont,15458.6,16326.2,17680.2,18797.4,19198.1,19945.8,21049.1,21477.4,...,31073.3,31960.2,33117.1,34838.0,37392.8,39552.8,41336.5,44058.6,46229.3,48079.2
47,51000,Virginia,199883.6,214025.7,231869.8,244314.3,251357.7,266325.2,284687.3,303288.9,...,444691.4,462372.2,479766.6,501770.8,530771.6,582077.9,604039.5,645405.9,681552.2,712992.6
48,53000,Washington,169365.4,179870.3,192317.8,197445.7,201073.1,209167.8,224342.9,232783.8,...,397270.6,423017.2,451609.2,484540.9,522862.2,572644.9,592733.0,637129.4,677934.6,715263.1
49,54000,West Virginia,37130.6,38078.6,40251.6,42750.3,44243.2,44952.8,46551.2,48854.3,...,68067.9,70797.6,74235.0,76725.0,80440.3,87322.5,88990.1,93771.0,97970.7,102315.6
50,55000,Wisconsin,143130.0,148737.0,158494.2,166593.2,171010.0,175794.3,183721.4,189779.2,...,270846.6,281979.5,295996.8,307947.5,327298.4,357005.4,365050.1,384719.8,403888.3,421498.1
51,56000,Wyoming,12615.1,13476.8,14545.3,15440.8,15905.3,16937.2,18287.4,20004.4,...,31090.1,32487.4,34025.2,35585.6,37602.9,41420.5,45259.3,48583.0,50815.4,52873.5