# Feature Selection
- In this file, I will be comparing different feature selection techniques on my data
- I am getting my feature selection ideas + code from [1.13. Feature selection](https://scikit-learn.org/stable/modules/feature_selection.html)

In [1]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

In [2]:
df = pd.read_csv("../data/POL_FINAL_DF.csv")

In [3]:
df.head()

,House Leaning,Senate Leaning,Average Leaning,LocYear,Geography,% >= HS,% >= Bachelor's,"Pov for 25yo<=, <HS","Pov for 25<=, >=Bachelor's",GeoFIPS,HFR,SNAP_rate,DPI_rate,PI_rate
0,0.142857,0.200000,0.171429,AL2010,0400000US01,0.821,0.219,0.300,0.041,1000,0.456,0.147621,0.082011,0.089287
1,-0.100000,0.000000,-0.050000,AK2010,0400000US02,0.910,0.279,0.177,0.028,2000,0.611,0.132925,0.128447,0.138935
2,-0.166667,-0.200000,-0.183333,AZ2010,0400000US04,0.856,0.259,0.301,0.046,4000,0.346,0.139955,0.085180,0.092639
3,0.430000,0.542857,0.486429,AR2010,0400000US05,0.829,0.195,0.267,0.039,5000,0.493,0.142676,0.077484,0.084426
4,0.250000,0.275000,0.262500,CA2010,0400000US06,0.807,0.301,0.253,0.049,6000,0.174,0.087893,0.115410,0.129771

In [4]:
info_df = df[["House Leaning", "Senate Leaning", "Average Leaning", "% >= HS", 
                     "% >= Bachelor's", "Pov for 25yo<=, <HS", "Pov for 25<=, >=Bachelor's",
                         "SNAP_rate", "DPI_rate", "PI_rate", "HFR"]]

In [5]:
info_df.head()

,House Leaning,Senate Leaning,Average Leaning,% >= HS,% >= Bachelor's,"Pov for 25yo<=, <HS","Pov for 25<=, >=Bachelor's",SNAP_rate,DPI_rate,PI_rate,HFR
0,0.142857,0.200000,0.171429,0.821,0.219,0.300,0.041,0.147621,0.082011,0.089287,0.456
1,-0.100000,0.000000,-0.050000,0.910,0.279,0.177,0.028,0.132925,0.128447,0.138935,0.611
2,-0.166667,-0.200000,-0.183333,0.856,0.259,0.301,0.046,0.139955,0.085180,0.092639,0.346
3,0.430000,0.542857,0.486429,0.829,0.195,0.267,0.039,0.142676,0.077484,0.084426,0.493
4,0.250000,0.275000,0.262500,0.807,0.301,0.253,0.049,0.087893,0.115410,0.129771,0.174

## Variance Threshold 
**From ScikitLearn:**
- VarianceThreshold is a simple baseline approach to feature selection. It removes all features whose variance doesn’t meet some threshold
- By default, it removes all zero-variance features, i.e. features that have the same value in all samples

In [13]:
from sklearn.feature_selection import VarianceThreshold

sel = VarianceThreshold(threshold=(.10))
sel.fit_transform(info_df)

array([[ 0.14285714,  0.2       ,  0.17142857],
       [-0.1       ,  0.        , -0.05      ],
       [-0.16666667, -0.2       , -0.18333333],
       ...,
       [-0.28      , -0.05882353, -0.16941176],
       [-0.27272727, -0.15151515, -0.21212121],
       [-0.7       , -0.73333333, -0.71666667]], shape=(343, 3))

In [14]:
print(sel.variances_)

[1.17393386e-01 1.45671966e-01 1.24869632e-01 1.00540809e-03
 2.52294423e-03 1.69040798e-03 7.60380114e-05 9.15161952e-04
 2.82211653e-04 4.28348678e-04 1.95959517e-02]

In [15]:
sel

VarianceThreshold(threshold=0.1)

In [16]:
kept_columns = info_df.columns[sel.get_support()]

In [17]:
print(list(kept_columns))

['House Leaning', 'Senate Leaning', 'Average Leaning']

## Univariate feature selection
**From ScikitLearn**
- Univariate feature selection works by selecting the best features based on univariate statistical tests.
- It can be seen as a preprocessing step to an estimator.
- Scikit-learn exposes feature selection routines as objects that implement the transform method

In [30]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import r_regression

In [31]:
X = info_df[["House Leaning", "Senate Leaning", "Average Leaning", "% >= HS", 
                     "% >= Bachelor's", "Pov for 25yo<=, <HS", "Pov for 25<=, >=Bachelor's",
                         "SNAP_rate", "DPI_rate", "PI_rate"]]
y = info_df["HFR"]

In [26]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 343 entries, 0 to 342
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   House Leaning               343 non-null    float64
 1   Senate Leaning              343 non-null    float64
 2   Average Leaning             343 non-null    float64
 3   % >= HS                     343 non-null    float64
 4   % >= Bachelor's             343 non-null    float64
 5   Pov for 25yo<=, <HS         343 non-null    float64
 6   Pov for 25<=, >=Bachelor's  343 non-null    float64
 7   SNAP_rate                   343 non-null    float64
 8   DPI_rate                    343 non-null    float64
 9   PI_rate                     343 non-null    float64
dtypes: float64(10)
memory usage: 26.9 KB

In [37]:
selector = SelectKBest(r_regression, k=3)
selector.fit(X, y)

selected_mask = selector.get_support()

selected_columns = X.columns[selected_mask]

In [38]:
selected_columns

Index(['% >= HS', 'Pov for 25yo<=, <HS', 'SNAP_rate'], dtype='str')

## L1 Based

In [42]:
from sklearn.linear_model import LassoCV

lasso = LassoCV(cv=5).fit(X.values, y.values)  # auto-selects best alpha
print(f"Best alpha: {lasso.alpha_}")

model = SelectFromModel(lasso, prefit=True)
X_new = model.transform(X.values)
print(X_new.shape)

Best alpha: 3.141646032373662e-05
(343, 8)

In [45]:
# Full summary
support = model.get_support()
for feature, kept in zip(X.columns, support):
    print(f"{'+' if kept else '-'} {feature}")

+ House Leaning
+ Senate Leaning
- Average Leaning
+ % >= HS
+ % >= Bachelor's
+ Pov for 25yo<=, <HS
+ Pov for 25<=, >=Bachelor's
+ SNAP_rate
- DPI_rate
+ PI_rate

so I don't know if this changed anything...